### ISSUE TITLE
Use AWS_PROFILE instead of AWS_DEFAULT_PROFILE

### ISSUE THREAD

**Issue by solarchad** [oh-my-fish/plugin-aws#3]
Would you be open to switching this to use AWS_PROFILE as the env var it sets instead of AWS_DEFAULT_PROFILE? I'd be happy to create the PR if so. Tools like Terraform look at AWS_PROFILE and not AWS_DEFAULT_PROFILE and AWS_PROFILE will also work with the CLI/boto.

**Comment by madsem** [comment]
Same issue here, using Spacefish, is also using `AWS_PROFILE`. Maybe it would be a good idea to just manage both env vars? That would make it compatible with everything, because I know tools like [aws-vault](https://github.com/99designs/aws-vault/) also use `AWS_PROFILE`, but the AWS documentation says `AWS_DEFAULT_PROFILE`

**Comment by madsem** [comment]
Okay yeah so it seems AWS_PROFILE is the env var for the currently used profile, while AWS_DEFAULT_PROFILE simply sets which one to use by default...

So AWS_PROFILE should be populated by the profile switcher :)
